faq_data = {
    "What is your return policy?": "You can return items within 30 days of purchase for a full refund.",
    "How can I track my order?": "You can track your order using the tracking link provided in your confirmation email.",
    "What payment methods do you accept?": "We accept credit cards, debit cards, and PayPal.",
    "How can I contact customer support?": "You can reach our customer support at support@example.com or call us at 123-456-7890.",
    "What shipping options are available?": "We offer standard and express shipping options.",
    "Can I change my order after placing it?": "You can change your order within 1 hour of placing it by contacting customer support.",
    "Do you offer gift wrapping services?": "Yes, we offer gift wrapping services at checkout for an additional fee.",
    "What should I do if I received a damaged item?": "Please contact our customer support immediately with your order details.",
    "What are your business hours?": "Our business hours are Monday to Friday, 9 AM to 5 PM.",
    "Do you ship internationally?": "Yes, we ship to select international locations. Please check our shipping policy for more details.",
    "How do I reset my password?": "To reset your password, go to the login page and click on 'Forgot Password'.",
    "Can I cancel my order?": "Yes, you can cancel your order within 1 hour of placing it.",
    "How do I create an account?": "To create an account, click on the 'Sign Up' button on the top right of our homepage and fill in the required details.",
    "What happens if I forget my account password?": "You can reset your password by clicking on 'Forgot Password' at the login page and following the instructions.",
    "Do I need an account to place an order?": "No, you can place an order as a guest, but creating an account will allow you to track your order and manage returns easily.",
    "Can I change my shipping address after placing an order?": "You can change your shipping address within 1 hour of placing the order by contacting customer support.",
    "How do I delete my account?": "Please contact our customer support to permanently delete your account.",
    "What are your shipping rates?": "Shipping rates depend on your location and chosen shipping option. You can view the shipping charges during checkout.",
    "How long does shipping take?": "Standard shipping takes 5-7 business days, while express shipping takes 2-3 business days.",
    "Can I track my international order?": "Yes, you will receive a tracking number once your international order has shipped.",
    "Why hasn’t my order shipped yet?": "It can take 1-2 business days to process your order before it is shipped. You will receive a notification once it ships.",
    "What should I do if my package is lost?": "If your package hasn't arrived within the estimated time frame, contact our support team for assistance.",
    "Can I exchange an item instead of returning it?": "Yes, you can exchange items by contacting our customer support team within 30 days of purchase.",
    "How long does it take to process a return?": "Returns are typically processed within 7-10 business days once we receive the item.",
    "How will I receive my refund?": "Refunds will be processed to your original payment method within 7-10 business days.",
    "Can I return an item I bought on sale?": "Yes, sale items can be returned as long as they meet the return criteria.",
    "What items are non-refundable?": "Personalized, final sale, and perishable items are non-refundable.",
    "Do you offer installment payment options?": "Yes, we offer installment payment options through PayPal and Klarna during checkout.",
    "Why was my payment declined?": "Payments can be declined for several reasons, including incorrect payment information or insufficient funds. Please check with your bank or payment provider.",
    "Can I pay with a gift card?": "Yes, you can use a gift card at checkout along with other payment methods.",
    "How do I apply a discount code?": "You can apply a discount code on the checkout page before completing your purchase.",
    "Can I place an order over the phone?": "Yes, you can place an order over the phone by contacting our customer support.",
    "Do your products come with a warranty?": "Yes, most of our products come with a 1-year manufacturer's warranty. Check the product page for more details.",
    "Can I get a product repaired if it's damaged?": "If your product is damaged, you can contact customer support to inquire about repair options.",
    "How do I find out if a product is in stock?": "Product availability is listed on the product page. You can also sign up for stock alerts if an item is out of stock.",
    "Do you offer product customization?": "Yes, we offer customization on select products. You can choose customization options on the product page.",
    "Where can I find product size charts?": "Size charts are available on each product page, below the product description.",
    "Why can't I log into my account?": "Make sure your email and password are correct. If you’re still having trouble, try resetting your password.",
    "How can I update my email address or password?": "You can update your email or password by logging into your account and navigating to the 'Account Settings' section.",
    "What should I do if I'm having technical issues with the website?": "If you experience technical issues, try clearing your browser cache or using a different browser. Contact support if the issue persists.",
    "How do I unsubscribe from your emails?": "To unsubscribe, click the 'Unsubscribe' link at the bottom of any of our promotional emails."
}
